// Filename: CLIENT.C                                       
// "PROJECT" Generated by WinMaker Pro.                     
// Author:   Geoff Caras                                    

// 
// ***********************************************************************
// Code in this file is initially generated by the Ansi C Switch-It Module.
// This file contains functions you can change
// to provide whatever functionality you require.
// 
// 
// 
// For more information,
// see the section "How code is generated" in the documentation.
// 
// ***********************************************************************
// 
 
#include "WINDOWS.H"
#include "COFFLOAD.H"  

WMPDEBUG
#include "CLIENT.WMC"
    
char       MonitorFile[256];
    
// ***************************************************************
//               Client Area Controls: CLIENT
// ***************************************************************
 
//  Startup procedure for client dialog box 
HWND BLD_ClientClFunc(HWND hWnd,UINT message,WPARAM wParam,LPARAM lParam)
    {
    return BLD_ClientClFuncDef(hWnd,(char *)NULL,message);
    }
 
 
//  Modeless dialog box procedure 
BOOL BLD_CALLBACK BLD_ClientClProc(HWND hDlg,UINT message,WPARAM wParam,LPARAM lParam)
    {
    WORD        wId;
 
    switch(message)
        {
    case WM_INITDIALOG:
        return BLD_ClientDlgDefault(hDlg,message,wParam,lParam);
        break;
 
    case WM_NCDESTROY:
        return BLD_ClientDlgDefault(hDlg,message,wParam,lParam);
        break;
 
    case WM_COMMAND:
        wId=LOWORD(wParam);
        switch(wId)
            {
        case IDOK:
            return BLD_ClientDlgDefault(hDlg,message,wParam,lParam);
            break;
        case IDCANCEL:
            return BLD_ClientDlgDefault(hDlg,message,wParam,lParam);
            break;
        default:
            return BLD_ClientDlgDefault(hDlg,message,wParam,lParam);
            break;
            }
        break;
 
    default:
        return BLD_ClientDlgDefault(hDlg,message,wParam,lParam);
        break;
        }
    return TRUE;//  Did process the message 
    }
 
 

 

// WINDOW INIT
HWND ucCreateWindow(DWORD *pWndStyle,DWORD *pWndStyleEx,int Coordinate[],PSTR *ppInfo)
    {
    // Insert your code here
    
    //  If you perform your own CreateWindow here,
    //  you have to return the handle to the created window.
    //  Return of 0 means the Ansi C SIM creates the main window.
    return 0;
    }
 
 
 
BOOL BLD_ApplicationExitAppExit() //  Exit Function for application 
    {
    // Clear out all old memory pointers...
    return TRUE;
    }
 
 
//  Function for interface to Windows on-line help 
BOOL BLD_FunctionHelp(HWND hWnd,UINT message,WPARAM wParam,LPARAM lParam)
    {
    BLDShowHelp(hWnd,HELP_HELPONHELP,0);
    return TRUE;
    }
 
 

 
 
// *****************************************************************************
// Common Dialog Open
// *****************************************************************************
 
BOOL cdClickedLOAD_MONITO(HWND hWnd,UINT Message,WPARAM wParam,LPARAM lParam)
    {
    OPENFILENAME         ofn;
    char                 szFile[256];
    UINT                 i;
    char                 chReplace;
    char                 szFilter[256];


    if(!IsDlgButtonChecked(hWnd, ID_LOAD_MONITOR)) {
        return TRUE;
    }

    if(GetFileAttributes((LPCTSTR)TEXT("SATMON.BIN")) != 0xffffffff) {
        strcpy(MonitorFile, "SATMON.BIN");
        return TRUE;
    }

    
    cd_ResetData((char *)&ofn,sizeof(OPENFILENAME));
    
    // FILTER
    lstrcpy(szFilter,"Binary Files (*.BIN)|*.BIN|All Files (*.*)|*.*|");
    chReplace            = '|';
    for (i = 0; szFilter[i] != 0; i++)
        {
        if (szFilter[i] == chReplace)
            szFilter[i]  = 0;
        }
    
    szFile[0]            = 0;
    
    ofn.lStructSize      = sizeof(OPENFILENAME);
    ofn.hwndOwner        = hWnd;
    ofn.hInstance        = hInst;
    ofn.lpstrFilter      = (LPSTR)szFilter;
    ofn.lpstrCustomFilter= NULL;
    ofn.nMaxCustFilter   = 0;
    ofn.nFilterIndex     = 0;
    ofn.lpstrFile        = (LPSTR)szFile;
    ofn.nMaxFile         = sizeof(szFile);
    ofn.lpstrFileTitle   = NULL;
    ofn.nMaxFileTitle    = 0;
    ofn.lpstrInitialDir  = NULL;
    ofn.lpstrTitle       = NULL;
    ofn.Flags            = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST | 
                           OFN_HIDEREADONLY;
    ofn.nFileOffset      = 0;
    ofn.nFileExtension   = 0;
    ofn.lpstrDefExt      = NULL;
    ofn.lCustData        = 0;
    ofn.lpfnHook         = NULL;
    ofn.lpTemplateName   = NULL;
    
    if (!GetOpenFileName(&ofn))
        return FALSE;
    
    // The selected file is in szFile
    strcpy(MonitorFile, szFile);

    return TRUE;
    }
 
 
// DIALOG BOX MESSAGE
BOOL ucCLIENTInitdialog(HWND hWnd,UINT message,WPARAM wParam,LPARAM lParam)
{
	// Insert your code here
	// This is the initialization of the HSIWin32 library &
	// code to ensure the ASPIWN32.DLL is loaded.
    EC      stat;
    HWND    hTmp;


    HSI_hwnd = hWnd;

    stat = HSI_Initialize(-1, -1);
    /* Make sure that the initialization went OK. If there was an error
     * print the message and exit...
    */
    ProcessHSIError(stat);

    /* Now the HSI library is initialized. 
     * Allocate a communication channel for all future transactions 
     * with CartDev...
    */
    // The monitor init now hides this from us...
    //stat = HSI_AllocateChannel(&CID);
    //ProcessHSIError(stat);

    /*  Initializing the monitor functions...
    */
    stat = MON_Initialize();

    ProcessHSIError(stat);

    
    if(ASPI_Inited != 0) {
        if(CartdevFound == TRUE) {
            hTmp = GetDlgItem(hWnd, ID_EDIT_WINDOW);
            
            MEditPrintF(hTmp, TEXT("%s"), TEXT(">>>"));
            MEditPrintF(hTmp, TEXT(">>> CartDev Found: Host #%d, SCSI Target #%d"), HSI_QHost, HSI_QID);
            MEditPrintF(hTmp, TEXT("%s"), TEXT(">>>"));
        } else {
            MEditPrintF(hTmp, TEXT("%s"), TEXT(">>>"));
            MEditPrintF(hTmp, TEXT("%s"), TEXT(">>> CartDev NOT Found!"));
            MEditPrintF(hTmp, TEXT("%s"), TEXT(">>>"));
        }
    }

	return TRUE;
}
