// Filename: GAME.C                                         
// "PROJECT" Generated by WinMaker Pro.                     
// Author:   Geoff Caras                                    

// 
// ***********************************************************************
// Code in this file is initially generated by the Ansi C Switch-It Module.
// This file contains functions you can change
// to provide whatever functionality you require.
// 
// 
// 
// For more information,
// see the section "How code is generated" in the documentation.
// 
// ***********************************************************************
// 
 
#include "WINDOWS.H"
#include "PROJECT.H"

WMPDEBUG
#include "GAME.WMC"
    
    
    
