// Filename: USERCODE.C                                     
// "PROJECT" Generated by WinMaker Pro.                     
// Author:   Geoff Caras                                    

// 
// ***********************************************************************
// Code in this file is initially generated by the Ansi C Switch-It Module.
// This file contains functions you can change
// to provide whatever functionality you require.
// 
// 
// 
// For more information,
// see the section "How code is generated" in the documentation.
// 
// ***********************************************************************
// 
 
#include "WINDOWS.H"
#include "COFFLOAD.H"  

WMPDEBUG
#include "USERCODE.WMC"
    
    
    
 
 
//  User Defined Code 
BOOL BLD_ExitUDCFunc(HWND hWnd,UINT message,WPARAM wParam,LPARAM lParam)
    {
    PostQuitMessage(WM_QUIT);
    return TRUE;
    }
 
 
//  Function for interface to Windows on-line help 
BOOL BLD_ContentsHelp(HWND hWnd,UINT message,WPARAM wParam,LPARAM lParam)
    {
    BLDShowHelp(hWnd,HELP_CONTENTS,0);
    return TRUE;
    }
 
 
//  Function for interface to Windows on-line help 
BOOL BLD_UsingHelpHelp(HWND hWnd,UINT message,WPARAM wParam,LPARAM lParam)
    {
    BLDShowHelp(hWnd,HELP_HELPONHELP,0);
    return TRUE;
    }
 
 
// *****************************************************************************
// Common Dialog Open
// *****************************************************************************
 
BOOL cdOpen(HWND hWnd,UINT Message,WPARAM wParam,LPARAM lParam)
    {
    OPENFILENAME         ofn;
    char                 szFile[256];
    UINT                 i;
    char                 chReplace;
    char                 szFilter[256];
    
    cd_ResetData((char *)&ofn,sizeof(OPENFILENAME));
    
    // FILTER
    lstrcpy(szFilter,"COFF Files (*.COF)|*.cof|All Files (*.*)|*.*|");
    chReplace            = '|';
    for (i = 0; szFilter[i] != 0; i++)
        {
        if (szFilter[i] == chReplace)
            szFilter[i]  = 0;
        }
    
    szFile[0]            = 0;
    
    ofn.lStructSize      = sizeof(OPENFILENAME);
    ofn.hwndOwner        = hWnd;
    ofn.hInstance        = hInst;
    ofn.lpstrFilter      = (LPSTR)szFilter;
    ofn.lpstrCustomFilter= NULL;
    ofn.nMaxCustFilter   = 0;
    ofn.nFilterIndex     = 0;
    ofn.lpstrFile        = (LPSTR)szFile;
    ofn.nMaxFile         = sizeof(szFile);
    ofn.lpstrFileTitle   = NULL;
    ofn.nMaxFileTitle    = 0;
    ofn.lpstrInitialDir  = NULL;
    ofn.lpstrTitle       = NULL;
    ofn.Flags            = OFN_FILEMUSTEXIST | OFN_PATHMUSTEXIST | 
                           OFN_HIDEREADONLY;
    ofn.nFileOffset      = 0;
    ofn.nFileExtension   = 0;
    ofn.lpstrDefExt      = NULL;
    ofn.lCustData        = 0;
    ofn.lpfnHook         = NULL;
    ofn.lpTemplateName   = NULL;
    
    if (!GetOpenFileName(&ofn))
        return FALSE;
  
    // The selected file is in szFile
    SendDlgItemMessage(hWnd, ID_FILESPEC, WM_SETTEXT, 0, (LPARAM)(LPCTSTR)szFile);

    return TRUE;
    }
