/******************************************
 *                                        *
 *   SMPC SAMPLE PROGRAM Version 0.56a    *
 *                                        *
 *    file : ssp.h                        *
 *                                        *
 *  author : s.uchida sega cs h/w r&d     *
 *                                        *
 *    date : 94/11/09                     *
 *                                        *
 ******************************************/

#include <string.h>
#include <stdio.h>

#include "machine.h"

#include "sega_xpt.h"
#include "sega_def.h"
#include "sega_scl.h"
#include "sega_spr.h"
#include "sega_int.h"

#include "sspdef.h"
#include "sspi.h"

